// src/Kendo/react-demo/src/App.js
import React, {Component} from 'react';
import '@progress/kendo-theme-default/dist/all.css';
import './App.css';
import categories from './categories.json';
import products from './products.json';
import { process } from '@progress/kendo-data-query';
import { Grid, GridColumn } from '@progress/kendo-react-grid';
import { DropDownList } from '@progress/kendo-react-dropdowns';
import { Window } from '@progress/kendo-react-dialogs';

class App extends Component {

  state = {
    dropdownlistCategory: null,
    gridDataState: {
      sort: [
        { field: "ProductName", dir: "asc" }
      ],
      skip: 0,
      take: 10
    },
    windowVisible: false,
    gridClickedRow: {}
  }

  handleDropDownChange = (e) => {
    let newDataState = { ...this.state.gridDataState }
    if (e.target.value.CategoryID !== null) {
      newDataState.filter = {
        logic: 'and',
        filters: [{ field: 'CategoryID', operator: 'eq', value: e.target.value.CategoryID }]
      }
      newDataState.skip = 0
    } else {
      newDataState.filter = []
      newDataState.skip = 0
    }
    this.setState({
      dropdownlistCategory: e.target.value.CategoryID,
      gridDataState: newDataState
    });
  }

  handleGridDataStateChange = (e) => {
    this.setState({gridDataState: e.dataState});
  }

  handleGridRowClick = (e) => {
    this.setState({
        windowVisible: true,
        gridClickedRow: e.dataItem
    });
  }

  closeWindow = (e) => {
    this.setState({
        windowVisible: false
    });
  }

  render() {
    return (
      <div className="kendo-react-getting-started">
        <h1>Hello Kendo UI for React!</h1>
        <p>
          <DropDownList
            data={categories}
            dataItemKey="CategoryID"
            textField="CategoryName"
            defaultItem={{CategoryID: null, CategoryName: "Product categories"}}
            onChange={this.handleDropDownChange}
            />
          &nbsp; Selected category ID: <strong>{this.state.dropdownlistCategory}</strong>
        </p>

        <Grid
          data={process(products, this.state.gridDataState)}
          pageable={true}
          sortable={true}
          {...this.state.gridDataState}
          onDataStateChange={this.handleGridDataStateChange}
          style={{ height: "400px" }}
          onRowClick={this.handleGridRowClick}>
          <GridColumn field="ProductName" title="Product Name" />
          <GridColumn field="UnitPrice" title="Price" format="{0:c}" />
          <GridColumn field="UnitsInStock" title="Units in Stock" />
          <GridColumn field="Discontinued" cell={checkboxColumn} />
        </Grid>

        {this.state.windowVisible &&
          <Window
            title="Product Details"
            onClose={this.closeWindow}
            height={250}>
            <dl>
              <dt>Product Name</dt>
              <dd>{this.state.gridClickedRow.ProductName}</dd>
              <dt>Product ID</dt>
              <dd>{this.state.gridClickedRow.ProductID}</dd>
              <dt>Quantity per Unit</dt>
              <dd>{this.state.gridClickedRow.QuantityPerUnit}</dd>
            </dl>
          </Window>
        }

      </div>
    );
  }
}

class checkboxColumn extends Component {
  render() {
    return (
        <td>
          <input type="checkbox" checked={this.props.dataItem[this.props.field]} disabled="disabled" />
        </td>
    );
  }
}

export default App;

// src/Kendo/angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { categories } from "./data.categories";
import { GridDataResult, PageChangeEvent } from "@progress/kendo-angular-grid";
import { SortDescriptor } from "@progress/kendo-data-query";
import { ProductService } from "./product.service";
import { Observable } from "rxjs";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [ProductService]
})

export class AppComponent {
  // used for the DropDownList
  public dropDownItems = categories;
  public defaultItem = { text: 'Filter by Category', value: null };

  // used for the Grid
  public gridItems!: Observable<GridDataResult>;
  public pageSize: number = 10;
  public skip: number = 0;
  public sortDescriptor: SortDescriptor[] = [];
  // public filterDescriptor: FilterDescriptor[] = [];
  public filterTerm: number | null = null;

  constructor(private service: ProductService) {
      this.loadGridItems();
  }

  public pageChange(event: PageChangeEvent): void {
      this.skip = event.skip;
      this.loadGridItems();
  }

  private loadGridItems(): void {
      this.gridItems = this.service.getProducts(this.skip, this.pageSize, this.sortDescriptor, this.filterTerm);
  }

  public handleSortChange(descriptor: SortDescriptor[]): void {
      this.sortDescriptor = descriptor;
      this.loadGridItems();
  }

  public handleFilterChange(item: { text: string; value: number | null }): void {
      this.filterTerm = item.value;
      this.skip = 0;
      this.loadGridItems();
  }
}

<div class="toolbar" role="banner">
  <img
    width="40"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
</div>

<div class="content" role="main">
  <h1>Hello Kendo UI for Angular!</h1>

  <p>
      <kendo-dropdownlist
          [data]="dropDownItems"
          textField="text"
          valueField="value"
          [defaultItem]="defaultItem"
          (valueChange)="handleFilterChange($event)"
      [style.width.px]="170"
      >
      </kendo-dropdownlist>
  </p>
  
  <kendo-grid
      [data]="(gridItems | async)!"
      [pageSize]="pageSize"
      [skip]="skip"
      [pageable]="true"
      (pageChange)="pageChange($event)"
      [sortable]="true"
      [sort]="sortDescriptor"
      (sortChange)="handleSortChange($event)"
      [height]="400"
  >
      <kendo-grid-column field="ProductID" title="ID" [width]="50"> </kendo-grid-column>
      <kendo-grid-column field="ProductName" title="Product Name"> </kendo-grid-column>
      <kendo-grid-column field="Category.CategoryName" title="Category"> </kendo-grid-column>
      <kendo-grid-column field="UnitPrice" title="Unit Price" [width]="140" format="{0:c}"> </kendo-grid-column>
      <kendo-grid-column field="Discontinued" [width]="140" filter="boolean">
          <ng-template kendoGridCellTemplate let-dataItem>
              <input type="checkbox" [checked]="dataItem.Discontinued" disabled />
          </ng-template>
      </kendo-grid-column>
  </kendo-grid>
  
  <h2>Resources</h2>
  
  <ul>
      <li>
          <a href="https://www.telerik.com/kendo-angular-ui/components/getting-started/"
              >Kendo UI for Angular - Getting Started Documentation</a
          >
      </li>
      <li><a href="https://github.com/telerik/kendo-angular-quickstart-cli">GitHub repo for this app</a></li>
      <li><a href="https://www.telerik.com/kendo-angular-ui/components/">Kendo UI for Angular Components</a></li>
  </ul>
</div>

<router-outlet></router-outlet>
